### ISSUE TITLE
track jumps to next street, ignores bike paths.

### ISSUE THREAD

**Issue by hlinden** [openstreetcam/openstreetcam.org#64] opened 2016-08-24 16:49 UTC
See [here](http://openstreetview.org/map/@51.714655800875754,8.76879036426544,17z), for example. In the attachment, I've marked the track I've actually followed. The app has created imagery for the next road and has ignored the bike paths entirely.

![bike](https://cloud.githubusercontent.com/assets/4718458/17939565/7580ebf0-6a2b-11e6-9333-6a1cccbcd846.png)

**Comment by ToeBee** [comment] 2016-12-10 06:13
This is a duplicate of #38

**Comment by martijnv-telenav** [comment] 2019-02-13 22:19
Closing as duplicate

**Closed by martijnv-telenav** 2019-02-13 22:19 UTC
