### ISSUE TITLE
Photos do not match track

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetcam.org#140] opened 2017-09-12 20:02 UTC
On http://openstreetcam.org/details/494559 the photos do not match the track.

**Comment by Kalepom** [comment] 2018-09-25 19:13
Same issue on this track https://openstreetcam.org/details/8811/2120
How can I warn the contributor or flag the picture/track?

**Comment by bogdans-telenav** [comment] 2019-02-14 21:08
This https://openstreetcam.org/details/8811/2120 was a bug on the upload scripts or on the upload GUI. The photos are all from the same track but they are really scrambled. This was fixed since then.
On the http://openstreetcam.org/details/494559 it was most likely a bug on the processing part for the waylens but this was fixed in the meanwhile.
@Kalepom there is no way to flag any bad image or sequence. You can add a new issue with your proposal. I will close this since these particular bugs do not currently reproduce.

**Closed by bogdans-telenav** 2019-02-14 21:08 UTC
