### ISSUE TITLE
openstreetcam .apk on Dropbox

### ISSUE THREAD

**Issue by alrs** [openstreetcam/openstreetcam.org#91] opened 2016-12-15 04:19 UTC
I'm using a phone that is not associated with a Google account, so I cannot install Dropbox from the Google Play store.

**Comment by james2432** [comment] 2016-12-15 10:50
Duplicate of: https://github.com/openstreetview/android/issues/60

**Comment by bobblkabb** [comment] 2017-05-10 13:26
Not available on dropbox anymore.

**Closed** 2019-05-21 10:10 UTC
Labels: duplicate, enhancement
