### ISSUE TITLE
Track binds to highway, while I bike cycleway and footway

### ISSUE THREAD

**Issue by Ilis** [openstreetcam/openstreetcam.org#67] opened 2016-08-25 07:44 UTC
Track binds to highway, while I bike cycleway and footway

http://openstreetview.org/details/14367/1

**Comment by james2432** [comment] 2016-08-25 09:39
Duplicate of #38

**Comment by martijnv-telenav** [comment] 2019-02-13 22:26
Closing as duplicate

**Closed by martijnv-telenav** 2019-02-13 22:26 UTC
