### ISSUE TITLE
snap-to-road feature impacts utility

### ISSUE THREAD

**Issue by rwelty1889** [openstreetcam/openstreetcam.org#153] opened 2018-03-01 21:08 UTC
i drove off the beaten path today to map some new, unmapped roads. fortunately i have osm track logger on another device, as OSC snapped some of the traces over to nearby, mapped roads. i'm not sure what a good remedy is, but this is a very real issue.

**Comment by james2432** [comment] 2018-03-01 21:33
bug is already open for this, only affects webpage. Josm and back en correctly geo code em

**Comment by alexandrui-telenav** [comment] 2018-03-02 06:09
hi @rwelty1889, as james mentioned this affects visualisation on the webage but the photos are placed correctly in editing tools and the track page on the website ( where we don't snap to roads ).
We have an improvement in the pipeline to do a better job at the snapping component to better handle offroad and pedestrian paths. That will fix also past tracks.

**Comment by rwelty1889** [comment] 2018-03-02 15:43
when the map underlying the web app is updated, will the view correct itself? and secondarily when is the map updated. OSM changes i made more than a month ago that should impact this still aren't showing up on the OSC website.

**Comment by alexandrui-telenav** [comment] 2018-03-06 15:33
Yes, allow me give you a peak behind the scenes. There are several components in the OSC ecosystem that work with OSM. Brace yourself, it's gonna get messy:

- Map matcher: snaps tracks to roads. Used for calculating points and coverage geometry ( the purple lines ). Uses version A of OSM, let's say. 

- Web tiles: map display for the website, just a canvas for the purple stuff. Version B of OSM.

- OSM compare: we recently introduced [traffic signs detections](http://blog.improve-osm.org/en/2018/02/detecting-traffic-signs-in-openstreetcam/) in certain areas. We're using OSM to check which traffic signs are different from OSM. Uses version C of OSM, the freshest.

- Maps SDK for the apps. Canvas for the purple stuff on mobile. Version B of OSM, same as the tiles.

Sounds like it's all over the place, I know. I would absolutely love everything to be in sync, but we're just not there yet. Except OSM compare we're reusing existing components with different pipelines and update cycles, but the point was to clarify the role of each and what happens when something updates. When we update the map matcher, the purple lines will change for the better. When we update the web tiles, the purple lines will be drawn on the updated map.

**Comment by martijnv-telenav** [comment] 2019-02-13 22:25
Duplicate of #38 -- let's discuss resolution there. Thanks for reporting @rwelty1889  (even if it was a long time ago)

**Closed by martijnv-telenav** 2019-02-13 22:25 UTC
